<!DOCTYPE html>
<html>
<head>
    <title>PDF Document</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&display=swap');
        
        body { 
            font-family: 'Roboto', Arial, sans-serif;
            margin: 0;
            padding: 30px;
            color: #333;
            line-height: 1.6;
        }
        
        .header { 
            text-align: center;
            margin-bottom: 30px;
            padding-bottom: 15px;
            border-bottom: 2px solid #4a90e2;
        }
        
        .header h1 {
            color: #2c3e50;
            margin: 0;
            font-size: 28px;
            font-weight: 700;
        }
        
        .content {
            margin: 20px 0;
        }
        
        .generated-at {
            text-align: right;
            color: #7f8c8d;
            font-size: 12px;
            margin-bottom: 20px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 25px 0;
            font-size: 14px;
            min-width: 600px;
            box-shadow: 0 0 20px rgba(0, 0, 0, 0.05);
            border-radius: 8px;
            overflow: hidden;
        }
        
        thead tr {
            background-color: #4a90e2;
            color: #ffffff;
            text-align: left;
            font-weight: 500;
            text-transform: uppercase;
            font-size: 13px;
            letter-spacing: 0.5px;
        }
        
        th, td {
            padding: 15px 18px;
            border: 1px solid #e0e0e0;
        }
        
        tbody tr {
            border-bottom: 1px solid #e0e0e0;
            transition: all 0.2s ease;
        }
        
        tbody tr:nth-of-type(even) {
            background-color: #f8f9fa;
        }
        
        tbody tr:last-of-type {
            border-bottom: 2px solid #4a90e2;
        }
        
        tbody tr:hover {
            background-color: #f1f7ff;
        }
        
        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #eee;
            font-size: 12px;
            color: #7f8c8d;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Posts Overview</h1>
    </div>
    
    <div class="generated-at">
        Generated at: {{ now()->format('F j, Y \a\t H:i') }}
    </div>
    
    <div class="content">
        <table>
            <thead>
                <tr>
                    <th style="width: 30%;">Title</th>
                    <th>Content</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($posts as $post)
                    <tr>
                        <td style="font-weight: 500; color: #2c3e50;">{{ $post->title }}</td>
                        <td style="color: #555;">{{ $post->body }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    
    <div class="footer">
        Document generated by Flaiment Laravel • {{ date('Y') }}
    </div>
</body>
</html>
